services:
  iac:
    build:
      context: ./iac
      dockerfile: ../Dockerfiles.d/iac/Dockerfile
      args:
        GID: "${GID:-1000}"
        UID: "${UID:-1000}"
    environment:
      AWS_PROFILE: ${AWS_PROFILE:-}
      TF_VAR_app_unique_id: ${APP_UNIQUE_ID}
      TF_VAR_aws_region: ${AWS_REGION}
      TF_VAR_aws_tf_state_bucket: ${AWS_TF_STATE_BUCKET}
      TF_VAR_aws_tf_state_region: ${AWS_TF_STATE_REGION}
      TF_VAR_azure_location: ${AZURE_LOCATION}
      TF_VAR_azure_subscription_id: ${ARM_SUBSCRIPTION_ID}
      TF_VAR_azure_tf_state_resource_group: ${AZURE_TF_STATE_RESOURCE_GROUP}
      TF_VAR_azure_tf_state_storage_account: ${AZURE_TF_STATE_STORAGE_ACCOUNT}
      TF_VAR_gcp_project_id: ${GOOGLE_PROJECT_ID}
      TF_VAR_gcp_region: ${GOOGLE_REGION}
      TF_VAR_gcp_zone: ${GOOGLE_ZONE}
      TF_VAR_google_tf_state_bucket: ${GOOGLE_TF_STATE_BUCKET}
      TF_VAR_base_domain_name: ${BASE_DOMAIN_NAME}
      TF_VAR_image_tag: ${IMAGE_TAG:-latest}
    volumes:
      - .:/work
      - ~/.aws:/mnt/.aws:ro
      - ~/.azure:/mnt/.azure:ro
      - ~/.config/gcloud:/mnt/.config/gcloud:ro
    working_dir: /work/iac
